#!/usr/bin/python3

#Need dict of Tab key/name values:
propteryTagToNameDict = {
	#
	#"AOD": "",#???
	"ARA": "Arkansas Razorbacks Alumni",
	"ARK": "Arkansas Razorbacks",
	"ASU": "App St. Mountaineers",
	"AUB": "Auburn Tigers",
	"AZB": "Arizona Bowl",
	"BEC": "Big East",
	"BNY": "Bike New York",
	"BSM": "Bassmaster",
	"BWS": "Bowl Bound",
	"CIB": "Guaranteed Rate",
	"COL": "Columbia Lions",
	"CSU": "Colorado State Rams",
	"DEL": "Delaware Blue Hens",
	"FIB": "Fiesta Bowl",
	"GEN": "General",
	"ISU": "Iowa State Cyclones",
	"KYD": "Kentucky Derby",
	"KYW": "Derby City Gaming",
	"LCF": "LouCity Football Club",
	"MCB": "Music City Bowl",
	"MIB": "Military Bowl",
	"MSU": "Michigan State Spartans",
	"MUO": "Miami RedHawks",
	"NYR": "NYRA",
	"OMI": "Ole Miss Rebels",
	"PIT": "Pitt Panthers",
	"PRO": "PRORODEO",
	"RLF": "Racing Louisville",
	"RUT": "Rutgers Scarlet Knights",
	"SFA": "Stephen F. Austin Lumberjacks",
	"SGB": "Sugar Bowl",
	"SUB": "Sugar Bowl",
	"SYR": "Syracuse Orange",
	"TWG": "The World Games",
	"UCO": "UConn Huskies",
	"UNC": "UNC Tar Heels",
	"UST": "USTA LEAGUES",
	"USV": "USA Volleyball",
	"WCC": "West Coast Conference",
	"WGW": "The World Games",
	"WSO": "Winston Salem Open",
	"WVU": "West Virginia Mountaineers"
}